# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Simple Blog Theme
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl:  "" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url:  "" # change this to the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Make sure to exclude 'vendor' from the build
exclude: [vendor, "Gemfile", "Gemfile.lock"]

# permalink: /:categories/:year/:month/:day/:title.html
# none is equivalent to /:title.html
# https://jekyllrb.com/docs/permalinks
permalink: /:title.html

google_analytics: 0000


t:
  en:
    latest-posts:  "Latest Posts"
    read-more:  "read more"
    on-word: "on"
    contact: "Contact"
    contact-page: "contact.md"
    read-time: "min read"
    comments: "comments"
    go-to-home-page: "Go to the Home Page"
    months:
      january: "Jan"
      february: "Feb"
      march: "Mar"
      april: "Apr"
      may: "May"
      june: "Jun"
      july: "Jul"
      august: "Aug"
      september: "Sep"
      october: "Oct"
      november: "Nov"
      december : "Dec"
  it:
    latest-posts:  "Ultimi Posts"
    read-more:  "leggi"
    on-word: "su"
    contact: "Contatta"
    contact-page: "contatta.md"
    read-time: "min di lettura"
    comments: "commenti"
    go-to-home-page: "Vai alla Pagina Iniziale"
    months:
      january: "Gen"
      february: "Feb"
      march: "Mar"
      april: "Apr"
      may: "Mag"
      june: "Giu"
      july: "Lug"
      august: "Ago"
      september: "Set"
      october: "Ott"
      november: "Nov"
      december : "Dic"

defaults:
  -
    scope:
      type: "posts"
    values:
      lang: "en"
      category: articles
